// ------------------------------------------------------------------------------
// Author: Sal Zaki
// <auto-generated>
//   This code has been auto-generated by the associated .tt file.
//   Any changes made to in this file will be lost when the file is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable

using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace Payment.Domain.ValueObjects;

/// <summary>
/// ISO4217 representation 281 of fiat currencies.
/// </summary>
/// <remarks> Currencies not included:
/// 'ANTARCTICA', 'INTERNATIONAL MONETARY FUND (IMF) ', 'MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP', 'PALESTINE, STATE OF', 'SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS "SUCRE"', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'ZZ01_Bond Markets Unit European_EURCO', 'ZZ02_Bond Markets Unit European_EMU-6', 'ZZ03_Bond Markets Unit European_EUA-9', 'ZZ04_Bond Markets Unit European_EUA-17', 'ZZ06_Testing_Code', 'ZZ07_No_Currency', 'ZZ08_Gold', 'ZZ09_Palladium', 'ZZ10_Platinum', 'ZZ11_Silver'
/// </remarks>
/// <remarks> Published On: 01/01/2023 00:00:00 </remarks>
/// <remarks> Build On: 12/06/2023 17:46:32 </remarks>
/// <remarks> Source: https://www.six-group.com/dam/download/financial-information/data-center/iso-currrency/lists/list-one.xml </remarks>
public partial record Currency
{

  /// <summary>
  /// ISO4217 currency representation of Afghani (AFN).
  /// </summary>
  /// <remarks> Country: AFGHANISTAN </remarks>
  /// <remarks> Name: Afghani </remarks>
  /// <remarks> Code: AFN </remarks>
  /// <remarks> Number: 971 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency AFN = Currency.Create("Afghani", "AFN", 971, 2, new []{ "AFGHANISTAN" });

  /// <summary>
  /// ISO4217 currency representation of Euro (EUR).
  /// </summary>
  /// <remarks> Countries: ÅLAND ISLANDS, ANDORRA, AUSTRIA, BELGIUM, CROATIA, CYPRUS, ESTONIA, EUROPEAN UNION, FINLAND, FRANCE, FRENCH GUIANA, FRENCH SOUTHERN TERRITORIES (THE), GERMANY, GREECE, GUADELOUPE, HOLY SEE (THE), IRELAND, ITALY, LATVIA, LITHUANIA, LUXEMBOURG, MALTA, MARTINIQUE, MAYOTTE, MONACO, MONTENEGRO, NETHERLANDS (THE), PORTUGAL, RÉUNION, SAINT BARTHÉLEMY, SAINT MARTIN (FRENCH PART), SAINT PIERRE AND MIQUELON, SAN MARINO, SLOVAKIA, SLOVENIA, SPAIN </remarks>
  /// <remarks> Name: Euro </remarks>
  /// <remarks> Code: EUR </remarks>
  /// <remarks> Number: 978 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency EUR = Currency.Create("Euro", "EUR", 978, 2, new []{ "ÅLAND ISLANDS", "ANDORRA", "AUSTRIA", "BELGIUM", "CROATIA", "CYPRUS", "ESTONIA", "EUROPEAN UNION", "FINLAND", "FRANCE", "FRENCH GUIANA", "FRENCH SOUTHERN TERRITORIES (THE)", "GERMANY", "GREECE", "GUADELOUPE", "HOLY SEE (THE)", "IRELAND", "ITALY", "LATVIA", "LITHUANIA", "LUXEMBOURG", "MALTA", "MARTINIQUE", "MAYOTTE", "MONACO", "MONTENEGRO", "NETHERLANDS (THE)", "PORTUGAL", "RÉUNION", "SAINT BARTHÉLEMY", "SAINT MARTIN (FRENCH PART)", "SAINT PIERRE AND MIQUELON", "SAN MARINO", "SLOVAKIA", "SLOVENIA", "SPAIN" });

  /// <summary>
  /// ISO4217 currency representation of Lek (ALL).
  /// </summary>
  /// <remarks> Country: ALBANIA </remarks>
  /// <remarks> Name: Lek </remarks>
  /// <remarks> Code: ALL </remarks>
  /// <remarks> Number: 8 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency ALL = Currency.Create("Lek", "ALL", 8, 2, new []{ "ALBANIA" });

  /// <summary>
  /// ISO4217 currency representation of Algerian Dinar (DZD).
  /// </summary>
  /// <remarks> Country: ALGERIA </remarks>
  /// <remarks> Name: Algerian Dinar </remarks>
  /// <remarks> Code: DZD </remarks>
  /// <remarks> Number: 12 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency DZD = Currency.Create("Algerian Dinar", "DZD", 12, 2, new []{ "ALGERIA" });

  /// <summary>
  /// ISO4217 currency representation of US Dollar (USD).
  /// </summary>
  /// <remarks> Countries: AMERICAN SAMOA, BONAIRE, SINT EUSTATIUS AND SABA, BRITISH INDIAN OCEAN TERRITORY (THE), ECUADOR, EL SALVADOR, GUAM, HAITI, MARSHALL ISLANDS (THE), MICRONESIA (FEDERATED STATES OF), NORTHERN MARIANA ISLANDS (THE), PALAU, PANAMA, PUERTO RICO, TIMOR-LESTE, TURKS AND CAICOS ISLANDS (THE), UNITED STATES MINOR OUTLYING ISLANDS (THE), UNITED STATES OF AMERICA (THE), VIRGIN ISLANDS (BRITISH), VIRGIN ISLANDS (U.S.) </remarks>
  /// <remarks> Name: US Dollar </remarks>
  /// <remarks> Code: USD </remarks>
  /// <remarks> Number: 840 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency USD = Currency.Create("US Dollar", "USD", 840, 2, new []{ "AMERICAN SAMOA", "BONAIRE, SINT EUSTATIUS AND SABA", "BRITISH INDIAN OCEAN TERRITORY (THE)", "ECUADOR", "EL SALVADOR", "GUAM", "HAITI", "MARSHALL ISLANDS (THE)", "MICRONESIA (FEDERATED STATES OF)", "NORTHERN MARIANA ISLANDS (THE)", "PALAU", "PANAMA", "PUERTO RICO", "TIMOR-LESTE", "TURKS AND CAICOS ISLANDS (THE)", "UNITED STATES MINOR OUTLYING ISLANDS (THE)", "UNITED STATES OF AMERICA (THE)", "VIRGIN ISLANDS (BRITISH)", "VIRGIN ISLANDS (U.S.)" });

  /// <summary>
  /// ISO4217 currency representation of Kwanza (AOA).
  /// </summary>
  /// <remarks> Country: ANGOLA </remarks>
  /// <remarks> Name: Kwanza </remarks>
  /// <remarks> Code: AOA </remarks>
  /// <remarks> Number: 973 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency AOA = Currency.Create("Kwanza", "AOA", 973, 2, new []{ "ANGOLA" });

  /// <summary>
  /// ISO4217 currency representation of East Caribbean Dollar (XCD).
  /// </summary>
  /// <remarks> Countries: ANGUILLA, ANTIGUA AND BARBUDA, DOMINICA, GRENADA, MONTSERRAT, SAINT KITTS AND NEVIS, SAINT LUCIA, SAINT VINCENT AND THE GRENADINES </remarks>
  /// <remarks> Name: East Caribbean Dollar </remarks>
  /// <remarks> Code: XCD </remarks>
  /// <remarks> Number: 951 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency XCD = Currency.Create("East Caribbean Dollar", "XCD", 951, 2, new []{ "ANGUILLA", "ANTIGUA AND BARBUDA", "DOMINICA", "GRENADA", "MONTSERRAT", "SAINT KITTS AND NEVIS", "SAINT LUCIA", "SAINT VINCENT AND THE GRENADINES" });

  /// <summary>
  /// ISO4217 currency representation of Argentine Peso (ARS).
  /// </summary>
  /// <remarks> Country: ARGENTINA </remarks>
  /// <remarks> Name: Argentine Peso </remarks>
  /// <remarks> Code: ARS </remarks>
  /// <remarks> Number: 32 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency ARS = Currency.Create("Argentine Peso", "ARS", 32, 2, new []{ "ARGENTINA" });

  /// <summary>
  /// ISO4217 currency representation of Armenian Dram (AMD).
  /// </summary>
  /// <remarks> Country: ARMENIA </remarks>
  /// <remarks> Name: Armenian Dram </remarks>
  /// <remarks> Code: AMD </remarks>
  /// <remarks> Number: 51 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency AMD = Currency.Create("Armenian Dram", "AMD", 51, 2, new []{ "ARMENIA" });

  /// <summary>
  /// ISO4217 currency representation of Aruban Florin (AWG).
  /// </summary>
  /// <remarks> Country: ARUBA </remarks>
  /// <remarks> Name: Aruban Florin </remarks>
  /// <remarks> Code: AWG </remarks>
  /// <remarks> Number: 533 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency AWG = Currency.Create("Aruban Florin", "AWG", 533, 2, new []{ "ARUBA" });

  /// <summary>
  /// ISO4217 currency representation of Australian Dollar (AUD).
  /// </summary>
  /// <remarks> Countries: AUSTRALIA, CHRISTMAS ISLAND, COCOS (KEELING) ISLANDS (THE), HEARD ISLAND AND McDONALD ISLANDS, KIRIBATI, NAURU, NORFOLK ISLAND, TUVALU </remarks>
  /// <remarks> Name: Australian Dollar </remarks>
  /// <remarks> Code: AUD </remarks>
  /// <remarks> Number: 36 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency AUD = Currency.Create("Australian Dollar", "AUD", 36, 2, new []{ "AUSTRALIA", "CHRISTMAS ISLAND", "COCOS (KEELING) ISLANDS (THE)", "HEARD ISLAND AND McDONALD ISLANDS", "KIRIBATI", "NAURU", "NORFOLK ISLAND", "TUVALU" });

  /// <summary>
  /// ISO4217 currency representation of Azerbaijan Manat (AZN).
  /// </summary>
  /// <remarks> Country: AZERBAIJAN </remarks>
  /// <remarks> Name: Azerbaijan Manat </remarks>
  /// <remarks> Code: AZN </remarks>
  /// <remarks> Number: 944 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency AZN = Currency.Create("Azerbaijan Manat", "AZN", 944, 2, new []{ "AZERBAIJAN" });

  /// <summary>
  /// ISO4217 currency representation of Bahamian Dollar (BSD).
  /// </summary>
  /// <remarks> Country: BAHAMAS (THE) </remarks>
  /// <remarks> Name: Bahamian Dollar </remarks>
  /// <remarks> Code: BSD </remarks>
  /// <remarks> Number: 44 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency BSD = Currency.Create("Bahamian Dollar", "BSD", 44, 2, new []{ "BAHAMAS (THE)" });

  /// <summary>
  /// ISO4217 currency representation of Bahraini Dinar (BHD).
  /// </summary>
  /// <remarks> Country: BAHRAIN </remarks>
  /// <remarks> Name: Bahraini Dinar </remarks>
  /// <remarks> Code: BHD </remarks>
  /// <remarks> Number: 48 </remarks>
  /// <remarks> Minor Units: 3 </remarks>
  public static readonly Currency BHD = Currency.Create("Bahraini Dinar", "BHD", 48, 3, new []{ "BAHRAIN" });

  /// <summary>
  /// ISO4217 currency representation of Taka (BDT).
  /// </summary>
  /// <remarks> Country: BANGLADESH </remarks>
  /// <remarks> Name: Taka </remarks>
  /// <remarks> Code: BDT </remarks>
  /// <remarks> Number: 50 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency BDT = Currency.Create("Taka", "BDT", 50, 2, new []{ "BANGLADESH" });

  /// <summary>
  /// ISO4217 currency representation of Barbados Dollar (BBD).
  /// </summary>
  /// <remarks> Country: BARBADOS </remarks>
  /// <remarks> Name: Barbados Dollar </remarks>
  /// <remarks> Code: BBD </remarks>
  /// <remarks> Number: 52 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency BBD = Currency.Create("Barbados Dollar", "BBD", 52, 2, new []{ "BARBADOS" });

  /// <summary>
  /// ISO4217 currency representation of Belarusian Ruble (BYN).
  /// </summary>
  /// <remarks> Country: BELARUS </remarks>
  /// <remarks> Name: Belarusian Ruble </remarks>
  /// <remarks> Code: BYN </remarks>
  /// <remarks> Number: 933 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency BYN = Currency.Create("Belarusian Ruble", "BYN", 933, 2, new []{ "BELARUS" });

  /// <summary>
  /// ISO4217 currency representation of Belize Dollar (BZD).
  /// </summary>
  /// <remarks> Country: BELIZE </remarks>
  /// <remarks> Name: Belize Dollar </remarks>
  /// <remarks> Code: BZD </remarks>
  /// <remarks> Number: 84 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency BZD = Currency.Create("Belize Dollar", "BZD", 84, 2, new []{ "BELIZE" });

  /// <summary>
  /// ISO4217 currency representation of CFA Franc BCEAO (XOF).
  /// </summary>
  /// <remarks> Countries: BENIN, BURKINA FASO, CÔTE D'IVOIRE, GUINEA-BISSAU, MALI, NIGER (THE), SENEGAL, TOGO </remarks>
  /// <remarks> Name: CFA Franc BCEAO </remarks>
  /// <remarks> Code: XOF </remarks>
  /// <remarks> Number: 952 </remarks>
  /// <remarks> Minor Units: 0 </remarks>
  public static readonly Currency XOF = Currency.Create("CFA Franc BCEAO", "XOF", 952, 0, new []{ "BENIN", "BURKINA FASO", "CÔTE D'IVOIRE", "GUINEA-BISSAU", "MALI", "NIGER (THE)", "SENEGAL", "TOGO" });

  /// <summary>
  /// ISO4217 currency representation of Bermudian Dollar (BMD).
  /// </summary>
  /// <remarks> Country: BERMUDA </remarks>
  /// <remarks> Name: Bermudian Dollar </remarks>
  /// <remarks> Code: BMD </remarks>
  /// <remarks> Number: 60 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency BMD = Currency.Create("Bermudian Dollar", "BMD", 60, 2, new []{ "BERMUDA" });

  /// <summary>
  /// ISO4217 currency representation of Indian Rupee (INR).
  /// </summary>
  /// <remarks> Countries: BHUTAN, INDIA </remarks>
  /// <remarks> Name: Indian Rupee </remarks>
  /// <remarks> Code: INR </remarks>
  /// <remarks> Number: 356 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency INR = Currency.Create("Indian Rupee", "INR", 356, 2, new []{ "BHUTAN", "INDIA" });

  /// <summary>
  /// ISO4217 currency representation of Ngultrum (BTN).
  /// </summary>
  /// <remarks> Country: BHUTAN </remarks>
  /// <remarks> Name: Ngultrum </remarks>
  /// <remarks> Code: BTN </remarks>
  /// <remarks> Number: 64 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency BTN = Currency.Create("Ngultrum", "BTN", 64, 2, new []{ "BHUTAN" });

  /// <summary>
  /// ISO4217 currency representation of Boliviano (BOB).
  /// </summary>
  /// <remarks> Country: BOLIVIA (PLURINATIONAL STATE OF) </remarks>
  /// <remarks> Name: Boliviano </remarks>
  /// <remarks> Code: BOB </remarks>
  /// <remarks> Number: 68 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency BOB = Currency.Create("Boliviano", "BOB", 68, 2, new []{ "BOLIVIA (PLURINATIONAL STATE OF)" });

  /// <summary>
  /// ISO4217 currency representation of Mvdol (BOV).
  /// </summary>
  /// <remarks> Country: BOLIVIA (PLURINATIONAL STATE OF) </remarks>
  /// <remarks> Name: Mvdol </remarks>
  /// <remarks> Code: BOV </remarks>
  /// <remarks> Number: 984 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency BOV = Currency.Create("Mvdol", "BOV", 984, 2, new []{ "BOLIVIA (PLURINATIONAL STATE OF)" });

  /// <summary>
  /// ISO4217 currency representation of Convertible Mark (BAM).
  /// </summary>
  /// <remarks> Country: BOSNIA AND HERZEGOVINA </remarks>
  /// <remarks> Name: Convertible Mark </remarks>
  /// <remarks> Code: BAM </remarks>
  /// <remarks> Number: 977 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency BAM = Currency.Create("Convertible Mark", "BAM", 977, 2, new []{ "BOSNIA AND HERZEGOVINA" });

  /// <summary>
  /// ISO4217 currency representation of Pula (BWP).
  /// </summary>
  /// <remarks> Country: BOTSWANA </remarks>
  /// <remarks> Name: Pula </remarks>
  /// <remarks> Code: BWP </remarks>
  /// <remarks> Number: 72 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency BWP = Currency.Create("Pula", "BWP", 72, 2, new []{ "BOTSWANA" });

  /// <summary>
  /// ISO4217 currency representation of Norwegian Krone (NOK).
  /// </summary>
  /// <remarks> Countries: BOUVET ISLAND, NORWAY, SVALBARD AND JAN MAYEN </remarks>
  /// <remarks> Name: Norwegian Krone </remarks>
  /// <remarks> Code: NOK </remarks>
  /// <remarks> Number: 578 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency NOK = Currency.Create("Norwegian Krone", "NOK", 578, 2, new []{ "BOUVET ISLAND", "NORWAY", "SVALBARD AND JAN MAYEN" });

  /// <summary>
  /// ISO4217 currency representation of Brazilian Real (BRL).
  /// </summary>
  /// <remarks> Country: BRAZIL </remarks>
  /// <remarks> Name: Brazilian Real </remarks>
  /// <remarks> Code: BRL </remarks>
  /// <remarks> Number: 986 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency BRL = Currency.Create("Brazilian Real", "BRL", 986, 2, new []{ "BRAZIL" });

  /// <summary>
  /// ISO4217 currency representation of Brunei Dollar (BND).
  /// </summary>
  /// <remarks> Country: BRUNEI DARUSSALAM </remarks>
  /// <remarks> Name: Brunei Dollar </remarks>
  /// <remarks> Code: BND </remarks>
  /// <remarks> Number: 96 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency BND = Currency.Create("Brunei Dollar", "BND", 96, 2, new []{ "BRUNEI DARUSSALAM" });

  /// <summary>
  /// ISO4217 currency representation of Bulgarian Lev (BGN).
  /// </summary>
  /// <remarks> Country: BULGARIA </remarks>
  /// <remarks> Name: Bulgarian Lev </remarks>
  /// <remarks> Code: BGN </remarks>
  /// <remarks> Number: 975 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency BGN = Currency.Create("Bulgarian Lev", "BGN", 975, 2, new []{ "BULGARIA" });

  /// <summary>
  /// ISO4217 currency representation of Burundi Franc (BIF).
  /// </summary>
  /// <remarks> Country: BURUNDI </remarks>
  /// <remarks> Name: Burundi Franc </remarks>
  /// <remarks> Code: BIF </remarks>
  /// <remarks> Number: 108 </remarks>
  /// <remarks> Minor Units: 0 </remarks>
  public static readonly Currency BIF = Currency.Create("Burundi Franc", "BIF", 108, 0, new []{ "BURUNDI" });

  /// <summary>
  /// ISO4217 currency representation of Cabo Verde Escudo (CVE).
  /// </summary>
  /// <remarks> Country: CABO VERDE </remarks>
  /// <remarks> Name: Cabo Verde Escudo </remarks>
  /// <remarks> Code: CVE </remarks>
  /// <remarks> Number: 132 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency CVE = Currency.Create("Cabo Verde Escudo", "CVE", 132, 2, new []{ "CABO VERDE" });

  /// <summary>
  /// ISO4217 currency representation of Riel (KHR).
  /// </summary>
  /// <remarks> Country: CAMBODIA </remarks>
  /// <remarks> Name: Riel </remarks>
  /// <remarks> Code: KHR </remarks>
  /// <remarks> Number: 116 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency KHR = Currency.Create("Riel", "KHR", 116, 2, new []{ "CAMBODIA" });

  /// <summary>
  /// ISO4217 currency representation of CFA Franc BEAC (XAF).
  /// </summary>
  /// <remarks> Countries: CAMEROON, CENTRAL AFRICAN REPUBLIC (THE), CHAD, CONGO (THE), EQUATORIAL GUINEA, GABON </remarks>
  /// <remarks> Name: CFA Franc BEAC </remarks>
  /// <remarks> Code: XAF </remarks>
  /// <remarks> Number: 950 </remarks>
  /// <remarks> Minor Units: 0 </remarks>
  public static readonly Currency XAF = Currency.Create("CFA Franc BEAC", "XAF", 950, 0, new []{ "CAMEROON", "CENTRAL AFRICAN REPUBLIC (THE)", "CHAD", "CONGO (THE)", "EQUATORIAL GUINEA", "GABON" });

  /// <summary>
  /// ISO4217 currency representation of Canadian Dollar (CAD).
  /// </summary>
  /// <remarks> Country: CANADA </remarks>
  /// <remarks> Name: Canadian Dollar </remarks>
  /// <remarks> Code: CAD </remarks>
  /// <remarks> Number: 124 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency CAD = Currency.Create("Canadian Dollar", "CAD", 124, 2, new []{ "CANADA" });

  /// <summary>
  /// ISO4217 currency representation of Cayman Islands Dollar (KYD).
  /// </summary>
  /// <remarks> Country: CAYMAN ISLANDS (THE) </remarks>
  /// <remarks> Name: Cayman Islands Dollar </remarks>
  /// <remarks> Code: KYD </remarks>
  /// <remarks> Number: 136 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency KYD = Currency.Create("Cayman Islands Dollar", "KYD", 136, 2, new []{ "CAYMAN ISLANDS (THE)" });

  /// <summary>
  /// ISO4217 currency representation of Chilean Peso (CLP).
  /// </summary>
  /// <remarks> Country: CHILE </remarks>
  /// <remarks> Name: Chilean Peso </remarks>
  /// <remarks> Code: CLP </remarks>
  /// <remarks> Number: 152 </remarks>
  /// <remarks> Minor Units: 0 </remarks>
  public static readonly Currency CLP = Currency.Create("Chilean Peso", "CLP", 152, 0, new []{ "CHILE" });

  /// <summary>
  /// ISO4217 currency representation of Unidad de Fomento (CLF).
  /// </summary>
  /// <remarks> Country: CHILE </remarks>
  /// <remarks> Name: Unidad de Fomento </remarks>
  /// <remarks> Code: CLF </remarks>
  /// <remarks> Number: 990 </remarks>
  /// <remarks> Minor Units: 4 </remarks>
  public static readonly Currency CLF = Currency.Create("Unidad de Fomento", "CLF", 990, 4, new []{ "CHILE" });

  /// <summary>
  /// ISO4217 currency representation of Yuan Renminbi (CNY).
  /// </summary>
  /// <remarks> Country: CHINA </remarks>
  /// <remarks> Name: Yuan Renminbi </remarks>
  /// <remarks> Code: CNY </remarks>
  /// <remarks> Number: 156 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency CNY = Currency.Create("Yuan Renminbi", "CNY", 156, 2, new []{ "CHINA" });

  /// <summary>
  /// ISO4217 currency representation of Colombian Peso (COP).
  /// </summary>
  /// <remarks> Country: COLOMBIA </remarks>
  /// <remarks> Name: Colombian Peso </remarks>
  /// <remarks> Code: COP </remarks>
  /// <remarks> Number: 170 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency COP = Currency.Create("Colombian Peso", "COP", 170, 2, new []{ "COLOMBIA" });

  /// <summary>
  /// ISO4217 currency representation of Unidad de Valor Real (COU).
  /// </summary>
  /// <remarks> Country: COLOMBIA </remarks>
  /// <remarks> Name: Unidad de Valor Real </remarks>
  /// <remarks> Code: COU </remarks>
  /// <remarks> Number: 970 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency COU = Currency.Create("Unidad de Valor Real", "COU", 970, 2, new []{ "COLOMBIA" });

  /// <summary>
  /// ISO4217 currency representation of Comorian Franc  (KMF).
  /// </summary>
  /// <remarks> Country: COMOROS (THE) </remarks>
  /// <remarks> Name: Comorian Franc  </remarks>
  /// <remarks> Code: KMF </remarks>
  /// <remarks> Number: 174 </remarks>
  /// <remarks> Minor Units: 0 </remarks>
  public static readonly Currency KMF = Currency.Create("Comorian Franc ", "KMF", 174, 0, new []{ "COMOROS (THE)" });

  /// <summary>
  /// ISO4217 currency representation of Congolese Franc (CDF).
  /// </summary>
  /// <remarks> Country: CONGO (THE DEMOCRATIC REPUBLIC OF THE) </remarks>
  /// <remarks> Name: Congolese Franc </remarks>
  /// <remarks> Code: CDF </remarks>
  /// <remarks> Number: 976 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency CDF = Currency.Create("Congolese Franc", "CDF", 976, 2, new []{ "CONGO (THE DEMOCRATIC REPUBLIC OF THE)" });

  /// <summary>
  /// ISO4217 currency representation of New Zealand Dollar (NZD).
  /// </summary>
  /// <remarks> Countries: COOK ISLANDS (THE), NEW ZEALAND, NIUE, PITCAIRN, TOKELAU </remarks>
  /// <remarks> Name: New Zealand Dollar </remarks>
  /// <remarks> Code: NZD </remarks>
  /// <remarks> Number: 554 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency NZD = Currency.Create("New Zealand Dollar", "NZD", 554, 2, new []{ "COOK ISLANDS (THE)", "NEW ZEALAND", "NIUE", "PITCAIRN", "TOKELAU" });

  /// <summary>
  /// ISO4217 currency representation of Costa Rican Colon (CRC).
  /// </summary>
  /// <remarks> Country: COSTA RICA </remarks>
  /// <remarks> Name: Costa Rican Colon </remarks>
  /// <remarks> Code: CRC </remarks>
  /// <remarks> Number: 188 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency CRC = Currency.Create("Costa Rican Colon", "CRC", 188, 2, new []{ "COSTA RICA" });

  /// <summary>
  /// ISO4217 currency representation of Cuban Peso (CUP).
  /// </summary>
  /// <remarks> Country: CUBA </remarks>
  /// <remarks> Name: Cuban Peso </remarks>
  /// <remarks> Code: CUP </remarks>
  /// <remarks> Number: 192 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency CUP = Currency.Create("Cuban Peso", "CUP", 192, 2, new []{ "CUBA" });

  /// <summary>
  /// ISO4217 currency representation of Peso Convertible (CUC).
  /// </summary>
  /// <remarks> Country: CUBA </remarks>
  /// <remarks> Name: Peso Convertible </remarks>
  /// <remarks> Code: CUC </remarks>
  /// <remarks> Number: 931 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency CUC = Currency.Create("Peso Convertible", "CUC", 931, 2, new []{ "CUBA" });

  /// <summary>
  /// ISO4217 currency representation of Netherlands Antillean Guilder (ANG).
  /// </summary>
  /// <remarks> Countries: CURAÇAO, SINT MAARTEN (DUTCH PART) </remarks>
  /// <remarks> Name: Netherlands Antillean Guilder </remarks>
  /// <remarks> Code: ANG </remarks>
  /// <remarks> Number: 532 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency ANG = Currency.Create("Netherlands Antillean Guilder", "ANG", 532, 2, new []{ "CURAÇAO", "SINT MAARTEN (DUTCH PART)" });

  /// <summary>
  /// ISO4217 currency representation of Czech Koruna (CZK).
  /// </summary>
  /// <remarks> Country: CZECHIA </remarks>
  /// <remarks> Name: Czech Koruna </remarks>
  /// <remarks> Code: CZK </remarks>
  /// <remarks> Number: 203 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency CZK = Currency.Create("Czech Koruna", "CZK", 203, 2, new []{ "CZECHIA" });

  /// <summary>
  /// ISO4217 currency representation of Danish Krone (DKK).
  /// </summary>
  /// <remarks> Countries: DENMARK, FAROE ISLANDS (THE), GREENLAND </remarks>
  /// <remarks> Name: Danish Krone </remarks>
  /// <remarks> Code: DKK </remarks>
  /// <remarks> Number: 208 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency DKK = Currency.Create("Danish Krone", "DKK", 208, 2, new []{ "DENMARK", "FAROE ISLANDS (THE)", "GREENLAND" });

  /// <summary>
  /// ISO4217 currency representation of Djibouti Franc (DJF).
  /// </summary>
  /// <remarks> Country: DJIBOUTI </remarks>
  /// <remarks> Name: Djibouti Franc </remarks>
  /// <remarks> Code: DJF </remarks>
  /// <remarks> Number: 262 </remarks>
  /// <remarks> Minor Units: 0 </remarks>
  public static readonly Currency DJF = Currency.Create("Djibouti Franc", "DJF", 262, 0, new []{ "DJIBOUTI" });

  /// <summary>
  /// ISO4217 currency representation of Dominican Peso (DOP).
  /// </summary>
  /// <remarks> Country: DOMINICAN REPUBLIC (THE) </remarks>
  /// <remarks> Name: Dominican Peso </remarks>
  /// <remarks> Code: DOP </remarks>
  /// <remarks> Number: 214 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency DOP = Currency.Create("Dominican Peso", "DOP", 214, 2, new []{ "DOMINICAN REPUBLIC (THE)" });

  /// <summary>
  /// ISO4217 currency representation of Egyptian Pound (EGP).
  /// </summary>
  /// <remarks> Country: EGYPT </remarks>
  /// <remarks> Name: Egyptian Pound </remarks>
  /// <remarks> Code: EGP </remarks>
  /// <remarks> Number: 818 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency EGP = Currency.Create("Egyptian Pound", "EGP", 818, 2, new []{ "EGYPT" });

  /// <summary>
  /// ISO4217 currency representation of El Salvador Colon (SVC).
  /// </summary>
  /// <remarks> Country: EL SALVADOR </remarks>
  /// <remarks> Name: El Salvador Colon </remarks>
  /// <remarks> Code: SVC </remarks>
  /// <remarks> Number: 222 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency SVC = Currency.Create("El Salvador Colon", "SVC", 222, 2, new []{ "EL SALVADOR" });

  /// <summary>
  /// ISO4217 currency representation of Nakfa (ERN).
  /// </summary>
  /// <remarks> Country: ERITREA </remarks>
  /// <remarks> Name: Nakfa </remarks>
  /// <remarks> Code: ERN </remarks>
  /// <remarks> Number: 232 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency ERN = Currency.Create("Nakfa", "ERN", 232, 2, new []{ "ERITREA" });

  /// <summary>
  /// ISO4217 currency representation of Lilangeni (SZL).
  /// </summary>
  /// <remarks> Country: ESWATINI </remarks>
  /// <remarks> Name: Lilangeni </remarks>
  /// <remarks> Code: SZL </remarks>
  /// <remarks> Number: 748 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency SZL = Currency.Create("Lilangeni", "SZL", 748, 2, new []{ "ESWATINI" });

  /// <summary>
  /// ISO4217 currency representation of Ethiopian Birr (ETB).
  /// </summary>
  /// <remarks> Country: ETHIOPIA </remarks>
  /// <remarks> Name: Ethiopian Birr </remarks>
  /// <remarks> Code: ETB </remarks>
  /// <remarks> Number: 230 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency ETB = Currency.Create("Ethiopian Birr", "ETB", 230, 2, new []{ "ETHIOPIA" });

  /// <summary>
  /// ISO4217 currency representation of Falkland Islands Pound (FKP).
  /// </summary>
  /// <remarks> Country: FALKLAND ISLANDS (THE) [MALVINAS] </remarks>
  /// <remarks> Name: Falkland Islands Pound </remarks>
  /// <remarks> Code: FKP </remarks>
  /// <remarks> Number: 238 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency FKP = Currency.Create("Falkland Islands Pound", "FKP", 238, 2, new []{ "FALKLAND ISLANDS (THE) [MALVINAS]" });

  /// <summary>
  /// ISO4217 currency representation of Fiji Dollar (FJD).
  /// </summary>
  /// <remarks> Country: FIJI </remarks>
  /// <remarks> Name: Fiji Dollar </remarks>
  /// <remarks> Code: FJD </remarks>
  /// <remarks> Number: 242 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency FJD = Currency.Create("Fiji Dollar", "FJD", 242, 2, new []{ "FIJI" });

  /// <summary>
  /// ISO4217 currency representation of CFP Franc (XPF).
  /// </summary>
  /// <remarks> Countries: FRENCH POLYNESIA, NEW CALEDONIA, WALLIS AND FUTUNA </remarks>
  /// <remarks> Name: CFP Franc </remarks>
  /// <remarks> Code: XPF </remarks>
  /// <remarks> Number: 953 </remarks>
  /// <remarks> Minor Units: 0 </remarks>
  public static readonly Currency XPF = Currency.Create("CFP Franc", "XPF", 953, 0, new []{ "FRENCH POLYNESIA", "NEW CALEDONIA", "WALLIS AND FUTUNA" });

  /// <summary>
  /// ISO4217 currency representation of Dalasi (GMD).
  /// </summary>
  /// <remarks> Country: GAMBIA (THE) </remarks>
  /// <remarks> Name: Dalasi </remarks>
  /// <remarks> Code: GMD </remarks>
  /// <remarks> Number: 270 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency GMD = Currency.Create("Dalasi", "GMD", 270, 2, new []{ "GAMBIA (THE)" });

  /// <summary>
  /// ISO4217 currency representation of Lari (GEL).
  /// </summary>
  /// <remarks> Country: GEORGIA </remarks>
  /// <remarks> Name: Lari </remarks>
  /// <remarks> Code: GEL </remarks>
  /// <remarks> Number: 981 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency GEL = Currency.Create("Lari", "GEL", 981, 2, new []{ "GEORGIA" });

  /// <summary>
  /// ISO4217 currency representation of Ghana Cedi (GHS).
  /// </summary>
  /// <remarks> Country: GHANA </remarks>
  /// <remarks> Name: Ghana Cedi </remarks>
  /// <remarks> Code: GHS </remarks>
  /// <remarks> Number: 936 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency GHS = Currency.Create("Ghana Cedi", "GHS", 936, 2, new []{ "GHANA" });

  /// <summary>
  /// ISO4217 currency representation of Gibraltar Pound (GIP).
  /// </summary>
  /// <remarks> Country: GIBRALTAR </remarks>
  /// <remarks> Name: Gibraltar Pound </remarks>
  /// <remarks> Code: GIP </remarks>
  /// <remarks> Number: 292 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency GIP = Currency.Create("Gibraltar Pound", "GIP", 292, 2, new []{ "GIBRALTAR" });

  /// <summary>
  /// ISO4217 currency representation of Quetzal (GTQ).
  /// </summary>
  /// <remarks> Country: GUATEMALA </remarks>
  /// <remarks> Name: Quetzal </remarks>
  /// <remarks> Code: GTQ </remarks>
  /// <remarks> Number: 320 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency GTQ = Currency.Create("Quetzal", "GTQ", 320, 2, new []{ "GUATEMALA" });

  /// <summary>
  /// ISO4217 currency representation of Pound Sterling (GBP).
  /// </summary>
  /// <remarks> Countries: GUERNSEY, ISLE OF MAN, JERSEY, UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE) </remarks>
  /// <remarks> Name: Pound Sterling </remarks>
  /// <remarks> Code: GBP </remarks>
  /// <remarks> Number: 826 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency GBP = Currency.Create("Pound Sterling", "GBP", 826, 2, new []{ "GUERNSEY", "ISLE OF MAN", "JERSEY", "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)" });

  /// <summary>
  /// ISO4217 currency representation of Guinean Franc (GNF).
  /// </summary>
  /// <remarks> Country: GUINEA </remarks>
  /// <remarks> Name: Guinean Franc </remarks>
  /// <remarks> Code: GNF </remarks>
  /// <remarks> Number: 324 </remarks>
  /// <remarks> Minor Units: 0 </remarks>
  public static readonly Currency GNF = Currency.Create("Guinean Franc", "GNF", 324, 0, new []{ "GUINEA" });

  /// <summary>
  /// ISO4217 currency representation of Guyana Dollar (GYD).
  /// </summary>
  /// <remarks> Country: GUYANA </remarks>
  /// <remarks> Name: Guyana Dollar </remarks>
  /// <remarks> Code: GYD </remarks>
  /// <remarks> Number: 328 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency GYD = Currency.Create("Guyana Dollar", "GYD", 328, 2, new []{ "GUYANA" });

  /// <summary>
  /// ISO4217 currency representation of Gourde (HTG).
  /// </summary>
  /// <remarks> Country: HAITI </remarks>
  /// <remarks> Name: Gourde </remarks>
  /// <remarks> Code: HTG </remarks>
  /// <remarks> Number: 332 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency HTG = Currency.Create("Gourde", "HTG", 332, 2, new []{ "HAITI" });

  /// <summary>
  /// ISO4217 currency representation of Lempira (HNL).
  /// </summary>
  /// <remarks> Country: HONDURAS </remarks>
  /// <remarks> Name: Lempira </remarks>
  /// <remarks> Code: HNL </remarks>
  /// <remarks> Number: 340 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency HNL = Currency.Create("Lempira", "HNL", 340, 2, new []{ "HONDURAS" });

  /// <summary>
  /// ISO4217 currency representation of Hong Kong Dollar (HKD).
  /// </summary>
  /// <remarks> Country: HONG KONG </remarks>
  /// <remarks> Name: Hong Kong Dollar </remarks>
  /// <remarks> Code: HKD </remarks>
  /// <remarks> Number: 344 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency HKD = Currency.Create("Hong Kong Dollar", "HKD", 344, 2, new []{ "HONG KONG" });

  /// <summary>
  /// ISO4217 currency representation of Forint (HUF).
  /// </summary>
  /// <remarks> Country: HUNGARY </remarks>
  /// <remarks> Name: Forint </remarks>
  /// <remarks> Code: HUF </remarks>
  /// <remarks> Number: 348 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency HUF = Currency.Create("Forint", "HUF", 348, 2, new []{ "HUNGARY" });

  /// <summary>
  /// ISO4217 currency representation of Iceland Krona (ISK).
  /// </summary>
  /// <remarks> Country: ICELAND </remarks>
  /// <remarks> Name: Iceland Krona </remarks>
  /// <remarks> Code: ISK </remarks>
  /// <remarks> Number: 352 </remarks>
  /// <remarks> Minor Units: 0 </remarks>
  public static readonly Currency ISK = Currency.Create("Iceland Krona", "ISK", 352, 0, new []{ "ICELAND" });

  /// <summary>
  /// ISO4217 currency representation of Rupiah (IDR).
  /// </summary>
  /// <remarks> Country: INDONESIA </remarks>
  /// <remarks> Name: Rupiah </remarks>
  /// <remarks> Code: IDR </remarks>
  /// <remarks> Number: 360 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency IDR = Currency.Create("Rupiah", "IDR", 360, 2, new []{ "INDONESIA" });

  /// <summary>
  /// ISO4217 currency representation of Iranian Rial (IRR).
  /// </summary>
  /// <remarks> Country: IRAN (ISLAMIC REPUBLIC OF) </remarks>
  /// <remarks> Name: Iranian Rial </remarks>
  /// <remarks> Code: IRR </remarks>
  /// <remarks> Number: 364 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency IRR = Currency.Create("Iranian Rial", "IRR", 364, 2, new []{ "IRAN (ISLAMIC REPUBLIC OF)" });

  /// <summary>
  /// ISO4217 currency representation of Iraqi Dinar (IQD).
  /// </summary>
  /// <remarks> Country: IRAQ </remarks>
  /// <remarks> Name: Iraqi Dinar </remarks>
  /// <remarks> Code: IQD </remarks>
  /// <remarks> Number: 368 </remarks>
  /// <remarks> Minor Units: 3 </remarks>
  public static readonly Currency IQD = Currency.Create("Iraqi Dinar", "IQD", 368, 3, new []{ "IRAQ" });

  /// <summary>
  /// ISO4217 currency representation of New Israeli Sheqel (ILS).
  /// </summary>
  /// <remarks> Country: ISRAEL </remarks>
  /// <remarks> Name: New Israeli Sheqel </remarks>
  /// <remarks> Code: ILS </remarks>
  /// <remarks> Number: 376 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency ILS = Currency.Create("New Israeli Sheqel", "ILS", 376, 2, new []{ "ISRAEL" });

  /// <summary>
  /// ISO4217 currency representation of Jamaican Dollar (JMD).
  /// </summary>
  /// <remarks> Country: JAMAICA </remarks>
  /// <remarks> Name: Jamaican Dollar </remarks>
  /// <remarks> Code: JMD </remarks>
  /// <remarks> Number: 388 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency JMD = Currency.Create("Jamaican Dollar", "JMD", 388, 2, new []{ "JAMAICA" });

  /// <summary>
  /// ISO4217 currency representation of Yen (JPY).
  /// </summary>
  /// <remarks> Country: JAPAN </remarks>
  /// <remarks> Name: Yen </remarks>
  /// <remarks> Code: JPY </remarks>
  /// <remarks> Number: 392 </remarks>
  /// <remarks> Minor Units: 0 </remarks>
  public static readonly Currency JPY = Currency.Create("Yen", "JPY", 392, 0, new []{ "JAPAN" });

  /// <summary>
  /// ISO4217 currency representation of Jordanian Dinar (JOD).
  /// </summary>
  /// <remarks> Country: JORDAN </remarks>
  /// <remarks> Name: Jordanian Dinar </remarks>
  /// <remarks> Code: JOD </remarks>
  /// <remarks> Number: 400 </remarks>
  /// <remarks> Minor Units: 3 </remarks>
  public static readonly Currency JOD = Currency.Create("Jordanian Dinar", "JOD", 400, 3, new []{ "JORDAN" });

  /// <summary>
  /// ISO4217 currency representation of Tenge (KZT).
  /// </summary>
  /// <remarks> Country: KAZAKHSTAN </remarks>
  /// <remarks> Name: Tenge </remarks>
  /// <remarks> Code: KZT </remarks>
  /// <remarks> Number: 398 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency KZT = Currency.Create("Tenge", "KZT", 398, 2, new []{ "KAZAKHSTAN" });

  /// <summary>
  /// ISO4217 currency representation of Kenyan Shilling (KES).
  /// </summary>
  /// <remarks> Country: KENYA </remarks>
  /// <remarks> Name: Kenyan Shilling </remarks>
  /// <remarks> Code: KES </remarks>
  /// <remarks> Number: 404 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency KES = Currency.Create("Kenyan Shilling", "KES", 404, 2, new []{ "KENYA" });

  /// <summary>
  /// ISO4217 currency representation of North Korean Won (KPW).
  /// </summary>
  /// <remarks> Country: KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF) </remarks>
  /// <remarks> Name: North Korean Won </remarks>
  /// <remarks> Code: KPW </remarks>
  /// <remarks> Number: 408 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency KPW = Currency.Create("North Korean Won", "KPW", 408, 2, new []{ "KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF)" });

  /// <summary>
  /// ISO4217 currency representation of Won (KRW).
  /// </summary>
  /// <remarks> Country: KOREA (THE REPUBLIC OF) </remarks>
  /// <remarks> Name: Won </remarks>
  /// <remarks> Code: KRW </remarks>
  /// <remarks> Number: 410 </remarks>
  /// <remarks> Minor Units: 0 </remarks>
  public static readonly Currency KRW = Currency.Create("Won", "KRW", 410, 0, new []{ "KOREA (THE REPUBLIC OF)" });

  /// <summary>
  /// ISO4217 currency representation of Kuwaiti Dinar (KWD).
  /// </summary>
  /// <remarks> Country: KUWAIT </remarks>
  /// <remarks> Name: Kuwaiti Dinar </remarks>
  /// <remarks> Code: KWD </remarks>
  /// <remarks> Number: 414 </remarks>
  /// <remarks> Minor Units: 3 </remarks>
  public static readonly Currency KWD = Currency.Create("Kuwaiti Dinar", "KWD", 414, 3, new []{ "KUWAIT" });

  /// <summary>
  /// ISO4217 currency representation of Som (KGS).
  /// </summary>
  /// <remarks> Country: KYRGYZSTAN </remarks>
  /// <remarks> Name: Som </remarks>
  /// <remarks> Code: KGS </remarks>
  /// <remarks> Number: 417 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency KGS = Currency.Create("Som", "KGS", 417, 2, new []{ "KYRGYZSTAN" });

  /// <summary>
  /// ISO4217 currency representation of Lao Kip (LAK).
  /// </summary>
  /// <remarks> Country: LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE) </remarks>
  /// <remarks> Name: Lao Kip </remarks>
  /// <remarks> Code: LAK </remarks>
  /// <remarks> Number: 418 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency LAK = Currency.Create("Lao Kip", "LAK", 418, 2, new []{ "LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE)" });

  /// <summary>
  /// ISO4217 currency representation of Lebanese Pound (LBP).
  /// </summary>
  /// <remarks> Country: LEBANON </remarks>
  /// <remarks> Name: Lebanese Pound </remarks>
  /// <remarks> Code: LBP </remarks>
  /// <remarks> Number: 422 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency LBP = Currency.Create("Lebanese Pound", "LBP", 422, 2, new []{ "LEBANON" });

  /// <summary>
  /// ISO4217 currency representation of Loti (LSL).
  /// </summary>
  /// <remarks> Country: LESOTHO </remarks>
  /// <remarks> Name: Loti </remarks>
  /// <remarks> Code: LSL </remarks>
  /// <remarks> Number: 426 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency LSL = Currency.Create("Loti", "LSL", 426, 2, new []{ "LESOTHO" });

  /// <summary>
  /// ISO4217 currency representation of Rand (ZAR).
  /// </summary>
  /// <remarks> Countries: LESOTHO, NAMIBIA, SOUTH AFRICA </remarks>
  /// <remarks> Name: Rand </remarks>
  /// <remarks> Code: ZAR </remarks>
  /// <remarks> Number: 710 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency ZAR = Currency.Create("Rand", "ZAR", 710, 2, new []{ "LESOTHO", "NAMIBIA", "SOUTH AFRICA" });

  /// <summary>
  /// ISO4217 currency representation of Liberian Dollar (LRD).
  /// </summary>
  /// <remarks> Country: LIBERIA </remarks>
  /// <remarks> Name: Liberian Dollar </remarks>
  /// <remarks> Code: LRD </remarks>
  /// <remarks> Number: 430 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency LRD = Currency.Create("Liberian Dollar", "LRD", 430, 2, new []{ "LIBERIA" });

  /// <summary>
  /// ISO4217 currency representation of Libyan Dinar (LYD).
  /// </summary>
  /// <remarks> Country: LIBYA </remarks>
  /// <remarks> Name: Libyan Dinar </remarks>
  /// <remarks> Code: LYD </remarks>
  /// <remarks> Number: 434 </remarks>
  /// <remarks> Minor Units: 3 </remarks>
  public static readonly Currency LYD = Currency.Create("Libyan Dinar", "LYD", 434, 3, new []{ "LIBYA" });

  /// <summary>
  /// ISO4217 currency representation of Swiss Franc (CHF).
  /// </summary>
  /// <remarks> Countries: LIECHTENSTEIN, SWITZERLAND </remarks>
  /// <remarks> Name: Swiss Franc </remarks>
  /// <remarks> Code: CHF </remarks>
  /// <remarks> Number: 756 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency CHF = Currency.Create("Swiss Franc", "CHF", 756, 2, new []{ "LIECHTENSTEIN", "SWITZERLAND" });

  /// <summary>
  /// ISO4217 currency representation of Pataca (MOP).
  /// </summary>
  /// <remarks> Country: MACAO </remarks>
  /// <remarks> Name: Pataca </remarks>
  /// <remarks> Code: MOP </remarks>
  /// <remarks> Number: 446 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency MOP = Currency.Create("Pataca", "MOP", 446, 2, new []{ "MACAO" });

  /// <summary>
  /// ISO4217 currency representation of Denar (MKD).
  /// </summary>
  /// <remarks> Country: NORTH MACEDONIA </remarks>
  /// <remarks> Name: Denar </remarks>
  /// <remarks> Code: MKD </remarks>
  /// <remarks> Number: 807 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency MKD = Currency.Create("Denar", "MKD", 807, 2, new []{ "NORTH MACEDONIA" });

  /// <summary>
  /// ISO4217 currency representation of Malagasy Ariary (MGA).
  /// </summary>
  /// <remarks> Country: MADAGASCAR </remarks>
  /// <remarks> Name: Malagasy Ariary </remarks>
  /// <remarks> Code: MGA </remarks>
  /// <remarks> Number: 969 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency MGA = Currency.Create("Malagasy Ariary", "MGA", 969, 2, new []{ "MADAGASCAR" });

  /// <summary>
  /// ISO4217 currency representation of Malawi Kwacha (MWK).
  /// </summary>
  /// <remarks> Country: MALAWI </remarks>
  /// <remarks> Name: Malawi Kwacha </remarks>
  /// <remarks> Code: MWK </remarks>
  /// <remarks> Number: 454 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency MWK = Currency.Create("Malawi Kwacha", "MWK", 454, 2, new []{ "MALAWI" });

  /// <summary>
  /// ISO4217 currency representation of Malaysian Ringgit (MYR).
  /// </summary>
  /// <remarks> Country: MALAYSIA </remarks>
  /// <remarks> Name: Malaysian Ringgit </remarks>
  /// <remarks> Code: MYR </remarks>
  /// <remarks> Number: 458 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency MYR = Currency.Create("Malaysian Ringgit", "MYR", 458, 2, new []{ "MALAYSIA" });

  /// <summary>
  /// ISO4217 currency representation of Rufiyaa (MVR).
  /// </summary>
  /// <remarks> Country: MALDIVES </remarks>
  /// <remarks> Name: Rufiyaa </remarks>
  /// <remarks> Code: MVR </remarks>
  /// <remarks> Number: 462 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency MVR = Currency.Create("Rufiyaa", "MVR", 462, 2, new []{ "MALDIVES" });

  /// <summary>
  /// ISO4217 currency representation of Ouguiya (MRU).
  /// </summary>
  /// <remarks> Country: MAURITANIA </remarks>
  /// <remarks> Name: Ouguiya </remarks>
  /// <remarks> Code: MRU </remarks>
  /// <remarks> Number: 929 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency MRU = Currency.Create("Ouguiya", "MRU", 929, 2, new []{ "MAURITANIA" });

  /// <summary>
  /// ISO4217 currency representation of Mauritius Rupee (MUR).
  /// </summary>
  /// <remarks> Country: MAURITIUS </remarks>
  /// <remarks> Name: Mauritius Rupee </remarks>
  /// <remarks> Code: MUR </remarks>
  /// <remarks> Number: 480 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency MUR = Currency.Create("Mauritius Rupee", "MUR", 480, 2, new []{ "MAURITIUS" });

  /// <summary>
  /// ISO4217 currency representation of Mexican Peso (MXN).
  /// </summary>
  /// <remarks> Country: MEXICO </remarks>
  /// <remarks> Name: Mexican Peso </remarks>
  /// <remarks> Code: MXN </remarks>
  /// <remarks> Number: 484 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency MXN = Currency.Create("Mexican Peso", "MXN", 484, 2, new []{ "MEXICO" });

  /// <summary>
  /// ISO4217 currency representation of Mexican Unidad de Inversion (UDI) (MXV).
  /// </summary>
  /// <remarks> Country: MEXICO </remarks>
  /// <remarks> Name: Mexican Unidad de Inversion (UDI) </remarks>
  /// <remarks> Code: MXV </remarks>
  /// <remarks> Number: 979 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency MXV = Currency.Create("Mexican Unidad de Inversion (UDI)", "MXV", 979, 2, new []{ "MEXICO" });

  /// <summary>
  /// ISO4217 currency representation of Moldovan Leu (MDL).
  /// </summary>
  /// <remarks> Country: MOLDOVA (THE REPUBLIC OF) </remarks>
  /// <remarks> Name: Moldovan Leu </remarks>
  /// <remarks> Code: MDL </remarks>
  /// <remarks> Number: 498 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency MDL = Currency.Create("Moldovan Leu", "MDL", 498, 2, new []{ "MOLDOVA (THE REPUBLIC OF)" });

  /// <summary>
  /// ISO4217 currency representation of Tugrik (MNT).
  /// </summary>
  /// <remarks> Country: MONGOLIA </remarks>
  /// <remarks> Name: Tugrik </remarks>
  /// <remarks> Code: MNT </remarks>
  /// <remarks> Number: 496 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency MNT = Currency.Create("Tugrik", "MNT", 496, 2, new []{ "MONGOLIA" });

  /// <summary>
  /// ISO4217 currency representation of Moroccan Dirham (MAD).
  /// </summary>
  /// <remarks> Countries: MOROCCO, WESTERN SAHARA </remarks>
  /// <remarks> Name: Moroccan Dirham </remarks>
  /// <remarks> Code: MAD </remarks>
  /// <remarks> Number: 504 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency MAD = Currency.Create("Moroccan Dirham", "MAD", 504, 2, new []{ "MOROCCO", "WESTERN SAHARA" });

  /// <summary>
  /// ISO4217 currency representation of Mozambique Metical (MZN).
  /// </summary>
  /// <remarks> Country: MOZAMBIQUE </remarks>
  /// <remarks> Name: Mozambique Metical </remarks>
  /// <remarks> Code: MZN </remarks>
  /// <remarks> Number: 943 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency MZN = Currency.Create("Mozambique Metical", "MZN", 943, 2, new []{ "MOZAMBIQUE" });

  /// <summary>
  /// ISO4217 currency representation of Kyat (MMK).
  /// </summary>
  /// <remarks> Country: MYANMAR </remarks>
  /// <remarks> Name: Kyat </remarks>
  /// <remarks> Code: MMK </remarks>
  /// <remarks> Number: 104 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency MMK = Currency.Create("Kyat", "MMK", 104, 2, new []{ "MYANMAR" });

  /// <summary>
  /// ISO4217 currency representation of Namibia Dollar (NAD).
  /// </summary>
  /// <remarks> Country: NAMIBIA </remarks>
  /// <remarks> Name: Namibia Dollar </remarks>
  /// <remarks> Code: NAD </remarks>
  /// <remarks> Number: 516 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency NAD = Currency.Create("Namibia Dollar", "NAD", 516, 2, new []{ "NAMIBIA" });

  /// <summary>
  /// ISO4217 currency representation of Nepalese Rupee (NPR).
  /// </summary>
  /// <remarks> Country: NEPAL </remarks>
  /// <remarks> Name: Nepalese Rupee </remarks>
  /// <remarks> Code: NPR </remarks>
  /// <remarks> Number: 524 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency NPR = Currency.Create("Nepalese Rupee", "NPR", 524, 2, new []{ "NEPAL" });

  /// <summary>
  /// ISO4217 currency representation of Cordoba Oro (NIO).
  /// </summary>
  /// <remarks> Country: NICARAGUA </remarks>
  /// <remarks> Name: Cordoba Oro </remarks>
  /// <remarks> Code: NIO </remarks>
  /// <remarks> Number: 558 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency NIO = Currency.Create("Cordoba Oro", "NIO", 558, 2, new []{ "NICARAGUA" });

  /// <summary>
  /// ISO4217 currency representation of Naira (NGN).
  /// </summary>
  /// <remarks> Country: NIGERIA </remarks>
  /// <remarks> Name: Naira </remarks>
  /// <remarks> Code: NGN </remarks>
  /// <remarks> Number: 566 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency NGN = Currency.Create("Naira", "NGN", 566, 2, new []{ "NIGERIA" });

  /// <summary>
  /// ISO4217 currency representation of Rial Omani (OMR).
  /// </summary>
  /// <remarks> Country: OMAN </remarks>
  /// <remarks> Name: Rial Omani </remarks>
  /// <remarks> Code: OMR </remarks>
  /// <remarks> Number: 512 </remarks>
  /// <remarks> Minor Units: 3 </remarks>
  public static readonly Currency OMR = Currency.Create("Rial Omani", "OMR", 512, 3, new []{ "OMAN" });

  /// <summary>
  /// ISO4217 currency representation of Pakistan Rupee (PKR).
  /// </summary>
  /// <remarks> Country: PAKISTAN </remarks>
  /// <remarks> Name: Pakistan Rupee </remarks>
  /// <remarks> Code: PKR </remarks>
  /// <remarks> Number: 586 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency PKR = Currency.Create("Pakistan Rupee", "PKR", 586, 2, new []{ "PAKISTAN" });

  /// <summary>
  /// ISO4217 currency representation of Balboa (PAB).
  /// </summary>
  /// <remarks> Country: PANAMA </remarks>
  /// <remarks> Name: Balboa </remarks>
  /// <remarks> Code: PAB </remarks>
  /// <remarks> Number: 590 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency PAB = Currency.Create("Balboa", "PAB", 590, 2, new []{ "PANAMA" });

  /// <summary>
  /// ISO4217 currency representation of Kina (PGK).
  /// </summary>
  /// <remarks> Country: PAPUA NEW GUINEA </remarks>
  /// <remarks> Name: Kina </remarks>
  /// <remarks> Code: PGK </remarks>
  /// <remarks> Number: 598 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency PGK = Currency.Create("Kina", "PGK", 598, 2, new []{ "PAPUA NEW GUINEA" });

  /// <summary>
  /// ISO4217 currency representation of Guarani (PYG).
  /// </summary>
  /// <remarks> Country: PARAGUAY </remarks>
  /// <remarks> Name: Guarani </remarks>
  /// <remarks> Code: PYG </remarks>
  /// <remarks> Number: 600 </remarks>
  /// <remarks> Minor Units: 0 </remarks>
  public static readonly Currency PYG = Currency.Create("Guarani", "PYG", 600, 0, new []{ "PARAGUAY" });

  /// <summary>
  /// ISO4217 currency representation of Sol (PEN).
  /// </summary>
  /// <remarks> Country: PERU </remarks>
  /// <remarks> Name: Sol </remarks>
  /// <remarks> Code: PEN </remarks>
  /// <remarks> Number: 604 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency PEN = Currency.Create("Sol", "PEN", 604, 2, new []{ "PERU" });

  /// <summary>
  /// ISO4217 currency representation of Philippine Peso (PHP).
  /// </summary>
  /// <remarks> Country: PHILIPPINES (THE) </remarks>
  /// <remarks> Name: Philippine Peso </remarks>
  /// <remarks> Code: PHP </remarks>
  /// <remarks> Number: 608 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency PHP = Currency.Create("Philippine Peso", "PHP", 608, 2, new []{ "PHILIPPINES (THE)" });

  /// <summary>
  /// ISO4217 currency representation of Zloty (PLN).
  /// </summary>
  /// <remarks> Country: POLAND </remarks>
  /// <remarks> Name: Zloty </remarks>
  /// <remarks> Code: PLN </remarks>
  /// <remarks> Number: 985 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency PLN = Currency.Create("Zloty", "PLN", 985, 2, new []{ "POLAND" });

  /// <summary>
  /// ISO4217 currency representation of Qatari Rial (QAR).
  /// </summary>
  /// <remarks> Country: QATAR </remarks>
  /// <remarks> Name: Qatari Rial </remarks>
  /// <remarks> Code: QAR </remarks>
  /// <remarks> Number: 634 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency QAR = Currency.Create("Qatari Rial", "QAR", 634, 2, new []{ "QATAR" });

  /// <summary>
  /// ISO4217 currency representation of Romanian Leu (RON).
  /// </summary>
  /// <remarks> Country: ROMANIA </remarks>
  /// <remarks> Name: Romanian Leu </remarks>
  /// <remarks> Code: RON </remarks>
  /// <remarks> Number: 946 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency RON = Currency.Create("Romanian Leu", "RON", 946, 2, new []{ "ROMANIA" });

  /// <summary>
  /// ISO4217 currency representation of Russian Ruble (RUB).
  /// </summary>
  /// <remarks> Country: RUSSIAN FEDERATION (THE) </remarks>
  /// <remarks> Name: Russian Ruble </remarks>
  /// <remarks> Code: RUB </remarks>
  /// <remarks> Number: 643 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency RUB = Currency.Create("Russian Ruble", "RUB", 643, 2, new []{ "RUSSIAN FEDERATION (THE)" });

  /// <summary>
  /// ISO4217 currency representation of Rwanda Franc (RWF).
  /// </summary>
  /// <remarks> Country: RWANDA </remarks>
  /// <remarks> Name: Rwanda Franc </remarks>
  /// <remarks> Code: RWF </remarks>
  /// <remarks> Number: 646 </remarks>
  /// <remarks> Minor Units: 0 </remarks>
  public static readonly Currency RWF = Currency.Create("Rwanda Franc", "RWF", 646, 0, new []{ "RWANDA" });

  /// <summary>
  /// ISO4217 currency representation of Saint Helena Pound (SHP).
  /// </summary>
  /// <remarks> Country: SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA </remarks>
  /// <remarks> Name: Saint Helena Pound </remarks>
  /// <remarks> Code: SHP </remarks>
  /// <remarks> Number: 654 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency SHP = Currency.Create("Saint Helena Pound", "SHP", 654, 2, new []{ "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA" });

  /// <summary>
  /// ISO4217 currency representation of Tala (WST).
  /// </summary>
  /// <remarks> Country: SAMOA </remarks>
  /// <remarks> Name: Tala </remarks>
  /// <remarks> Code: WST </remarks>
  /// <remarks> Number: 882 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency WST = Currency.Create("Tala", "WST", 882, 2, new []{ "SAMOA" });

  /// <summary>
  /// ISO4217 currency representation of Dobra (STN).
  /// </summary>
  /// <remarks> Country: SAO TOME AND PRINCIPE </remarks>
  /// <remarks> Name: Dobra </remarks>
  /// <remarks> Code: STN </remarks>
  /// <remarks> Number: 930 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency STN = Currency.Create("Dobra", "STN", 930, 2, new []{ "SAO TOME AND PRINCIPE" });

  /// <summary>
  /// ISO4217 currency representation of Saudi Riyal (SAR).
  /// </summary>
  /// <remarks> Country: SAUDI ARABIA </remarks>
  /// <remarks> Name: Saudi Riyal </remarks>
  /// <remarks> Code: SAR </remarks>
  /// <remarks> Number: 682 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency SAR = Currency.Create("Saudi Riyal", "SAR", 682, 2, new []{ "SAUDI ARABIA" });

  /// <summary>
  /// ISO4217 currency representation of Serbian Dinar (RSD).
  /// </summary>
  /// <remarks> Country: SERBIA </remarks>
  /// <remarks> Name: Serbian Dinar </remarks>
  /// <remarks> Code: RSD </remarks>
  /// <remarks> Number: 941 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency RSD = Currency.Create("Serbian Dinar", "RSD", 941, 2, new []{ "SERBIA" });

  /// <summary>
  /// ISO4217 currency representation of Seychelles Rupee (SCR).
  /// </summary>
  /// <remarks> Country: SEYCHELLES </remarks>
  /// <remarks> Name: Seychelles Rupee </remarks>
  /// <remarks> Code: SCR </remarks>
  /// <remarks> Number: 690 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency SCR = Currency.Create("Seychelles Rupee", "SCR", 690, 2, new []{ "SEYCHELLES" });

  /// <summary>
  /// ISO4217 currency representation of Leone (SLL).
  /// </summary>
  /// <remarks> Country: SIERRA LEONE </remarks>
  /// <remarks> Name: Leone </remarks>
  /// <remarks> Code: SLL </remarks>
  /// <remarks> Number: 694 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency SLL = Currency.Create("Leone", "SLL", 694, 2, new []{ "SIERRA LEONE" });

  /// <summary>
  /// ISO4217 currency representation of Leone (SLE).
  /// </summary>
  /// <remarks> Country: SIERRA LEONE </remarks>
  /// <remarks> Name: Leone </remarks>
  /// <remarks> Code: SLE </remarks>
  /// <remarks> Number: 925 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency SLE = Currency.Create("Leone", "SLE", 925, 2, new []{ "SIERRA LEONE" });

  /// <summary>
  /// ISO4217 currency representation of Singapore Dollar (SGD).
  /// </summary>
  /// <remarks> Country: SINGAPORE </remarks>
  /// <remarks> Name: Singapore Dollar </remarks>
  /// <remarks> Code: SGD </remarks>
  /// <remarks> Number: 702 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency SGD = Currency.Create("Singapore Dollar", "SGD", 702, 2, new []{ "SINGAPORE" });

  /// <summary>
  /// ISO4217 currency representation of Solomon Islands Dollar (SBD).
  /// </summary>
  /// <remarks> Country: SOLOMON ISLANDS </remarks>
  /// <remarks> Name: Solomon Islands Dollar </remarks>
  /// <remarks> Code: SBD </remarks>
  /// <remarks> Number: 90 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency SBD = Currency.Create("Solomon Islands Dollar", "SBD", 90, 2, new []{ "SOLOMON ISLANDS" });

  /// <summary>
  /// ISO4217 currency representation of Somali Shilling (SOS).
  /// </summary>
  /// <remarks> Country: SOMALIA </remarks>
  /// <remarks> Name: Somali Shilling </remarks>
  /// <remarks> Code: SOS </remarks>
  /// <remarks> Number: 706 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency SOS = Currency.Create("Somali Shilling", "SOS", 706, 2, new []{ "SOMALIA" });

  /// <summary>
  /// ISO4217 currency representation of South Sudanese Pound (SSP).
  /// </summary>
  /// <remarks> Country: SOUTH SUDAN </remarks>
  /// <remarks> Name: South Sudanese Pound </remarks>
  /// <remarks> Code: SSP </remarks>
  /// <remarks> Number: 728 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency SSP = Currency.Create("South Sudanese Pound", "SSP", 728, 2, new []{ "SOUTH SUDAN" });

  /// <summary>
  /// ISO4217 currency representation of Sri Lanka Rupee (LKR).
  /// </summary>
  /// <remarks> Country: SRI LANKA </remarks>
  /// <remarks> Name: Sri Lanka Rupee </remarks>
  /// <remarks> Code: LKR </remarks>
  /// <remarks> Number: 144 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency LKR = Currency.Create("Sri Lanka Rupee", "LKR", 144, 2, new []{ "SRI LANKA" });

  /// <summary>
  /// ISO4217 currency representation of Sudanese Pound (SDG).
  /// </summary>
  /// <remarks> Country: SUDAN (THE) </remarks>
  /// <remarks> Name: Sudanese Pound </remarks>
  /// <remarks> Code: SDG </remarks>
  /// <remarks> Number: 938 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency SDG = Currency.Create("Sudanese Pound", "SDG", 938, 2, new []{ "SUDAN (THE)" });

  /// <summary>
  /// ISO4217 currency representation of Surinam Dollar (SRD).
  /// </summary>
  /// <remarks> Country: SURINAME </remarks>
  /// <remarks> Name: Surinam Dollar </remarks>
  /// <remarks> Code: SRD </remarks>
  /// <remarks> Number: 968 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency SRD = Currency.Create("Surinam Dollar", "SRD", 968, 2, new []{ "SURINAME" });

  /// <summary>
  /// ISO4217 currency representation of Swedish Krona (SEK).
  /// </summary>
  /// <remarks> Country: SWEDEN </remarks>
  /// <remarks> Name: Swedish Krona </remarks>
  /// <remarks> Code: SEK </remarks>
  /// <remarks> Number: 752 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency SEK = Currency.Create("Swedish Krona", "SEK", 752, 2, new []{ "SWEDEN" });

  /// <summary>
  /// ISO4217 currency representation of WIR Euro (CHE).
  /// </summary>
  /// <remarks> Country: SWITZERLAND </remarks>
  /// <remarks> Name: WIR Euro </remarks>
  /// <remarks> Code: CHE </remarks>
  /// <remarks> Number: 947 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency CHE = Currency.Create("WIR Euro", "CHE", 947, 2, new []{ "SWITZERLAND" });

  /// <summary>
  /// ISO4217 currency representation of WIR Franc (CHW).
  /// </summary>
  /// <remarks> Country: SWITZERLAND </remarks>
  /// <remarks> Name: WIR Franc </remarks>
  /// <remarks> Code: CHW </remarks>
  /// <remarks> Number: 948 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency CHW = Currency.Create("WIR Franc", "CHW", 948, 2, new []{ "SWITZERLAND" });

  /// <summary>
  /// ISO4217 currency representation of Syrian Pound (SYP).
  /// </summary>
  /// <remarks> Country: SYRIAN ARAB REPUBLIC </remarks>
  /// <remarks> Name: Syrian Pound </remarks>
  /// <remarks> Code: SYP </remarks>
  /// <remarks> Number: 760 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency SYP = Currency.Create("Syrian Pound", "SYP", 760, 2, new []{ "SYRIAN ARAB REPUBLIC" });

  /// <summary>
  /// ISO4217 currency representation of New Taiwan Dollar (TWD).
  /// </summary>
  /// <remarks> Country: TAIWAN (PROVINCE OF CHINA) </remarks>
  /// <remarks> Name: New Taiwan Dollar </remarks>
  /// <remarks> Code: TWD </remarks>
  /// <remarks> Number: 901 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency TWD = Currency.Create("New Taiwan Dollar", "TWD", 901, 2, new []{ "TAIWAN (PROVINCE OF CHINA)" });

  /// <summary>
  /// ISO4217 currency representation of Somoni (TJS).
  /// </summary>
  /// <remarks> Country: TAJIKISTAN </remarks>
  /// <remarks> Name: Somoni </remarks>
  /// <remarks> Code: TJS </remarks>
  /// <remarks> Number: 972 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency TJS = Currency.Create("Somoni", "TJS", 972, 2, new []{ "TAJIKISTAN" });

  /// <summary>
  /// ISO4217 currency representation of Tanzanian Shilling (TZS).
  /// </summary>
  /// <remarks> Country: TANZANIA, UNITED REPUBLIC OF </remarks>
  /// <remarks> Name: Tanzanian Shilling </remarks>
  /// <remarks> Code: TZS </remarks>
  /// <remarks> Number: 834 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency TZS = Currency.Create("Tanzanian Shilling", "TZS", 834, 2, new []{ "TANZANIA, UNITED REPUBLIC OF" });

  /// <summary>
  /// ISO4217 currency representation of Baht (THB).
  /// </summary>
  /// <remarks> Country: THAILAND </remarks>
  /// <remarks> Name: Baht </remarks>
  /// <remarks> Code: THB </remarks>
  /// <remarks> Number: 764 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency THB = Currency.Create("Baht", "THB", 764, 2, new []{ "THAILAND" });

  /// <summary>
  /// ISO4217 currency representation of Pa’anga (TOP).
  /// </summary>
  /// <remarks> Country: TONGA </remarks>
  /// <remarks> Name: Pa’anga </remarks>
  /// <remarks> Code: TOP </remarks>
  /// <remarks> Number: 776 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency TOP = Currency.Create("Pa’anga", "TOP", 776, 2, new []{ "TONGA" });

  /// <summary>
  /// ISO4217 currency representation of Trinidad and Tobago Dollar (TTD).
  /// </summary>
  /// <remarks> Country: TRINIDAD AND TOBAGO </remarks>
  /// <remarks> Name: Trinidad and Tobago Dollar </remarks>
  /// <remarks> Code: TTD </remarks>
  /// <remarks> Number: 780 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency TTD = Currency.Create("Trinidad and Tobago Dollar", "TTD", 780, 2, new []{ "TRINIDAD AND TOBAGO" });

  /// <summary>
  /// ISO4217 currency representation of Tunisian Dinar (TND).
  /// </summary>
  /// <remarks> Country: TUNISIA </remarks>
  /// <remarks> Name: Tunisian Dinar </remarks>
  /// <remarks> Code: TND </remarks>
  /// <remarks> Number: 788 </remarks>
  /// <remarks> Minor Units: 3 </remarks>
  public static readonly Currency TND = Currency.Create("Tunisian Dinar", "TND", 788, 3, new []{ "TUNISIA" });

  /// <summary>
  /// ISO4217 currency representation of Turkish Lira (TRY).
  /// </summary>
  /// <remarks> Country: TÜRKİYE </remarks>
  /// <remarks> Name: Turkish Lira </remarks>
  /// <remarks> Code: TRY </remarks>
  /// <remarks> Number: 949 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency TRY = Currency.Create("Turkish Lira", "TRY", 949, 2, new []{ "TÜRKİYE" });

  /// <summary>
  /// ISO4217 currency representation of Turkmenistan New Manat (TMT).
  /// </summary>
  /// <remarks> Country: TURKMENISTAN </remarks>
  /// <remarks> Name: Turkmenistan New Manat </remarks>
  /// <remarks> Code: TMT </remarks>
  /// <remarks> Number: 934 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency TMT = Currency.Create("Turkmenistan New Manat", "TMT", 934, 2, new []{ "TURKMENISTAN" });

  /// <summary>
  /// ISO4217 currency representation of Uganda Shilling (UGX).
  /// </summary>
  /// <remarks> Country: UGANDA </remarks>
  /// <remarks> Name: Uganda Shilling </remarks>
  /// <remarks> Code: UGX </remarks>
  /// <remarks> Number: 800 </remarks>
  /// <remarks> Minor Units: 0 </remarks>
  public static readonly Currency UGX = Currency.Create("Uganda Shilling", "UGX", 800, 0, new []{ "UGANDA" });

  /// <summary>
  /// ISO4217 currency representation of Hryvnia (UAH).
  /// </summary>
  /// <remarks> Country: UKRAINE </remarks>
  /// <remarks> Name: Hryvnia </remarks>
  /// <remarks> Code: UAH </remarks>
  /// <remarks> Number: 980 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency UAH = Currency.Create("Hryvnia", "UAH", 980, 2, new []{ "UKRAINE" });

  /// <summary>
  /// ISO4217 currency representation of UAE Dirham (AED).
  /// </summary>
  /// <remarks> Country: UNITED ARAB EMIRATES (THE) </remarks>
  /// <remarks> Name: UAE Dirham </remarks>
  /// <remarks> Code: AED </remarks>
  /// <remarks> Number: 784 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency AED = Currency.Create("UAE Dirham", "AED", 784, 2, new []{ "UNITED ARAB EMIRATES (THE)" });

  /// <summary>
  /// ISO4217 currency representation of US Dollar (Next day) (USN).
  /// </summary>
  /// <remarks> Country: UNITED STATES OF AMERICA (THE) </remarks>
  /// <remarks> Name: US Dollar (Next day) </remarks>
  /// <remarks> Code: USN </remarks>
  /// <remarks> Number: 997 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency USN = Currency.Create("US Dollar (Next day)", "USN", 997, 2, new []{ "UNITED STATES OF AMERICA (THE)" });

  /// <summary>
  /// ISO4217 currency representation of Peso Uruguayo (UYU).
  /// </summary>
  /// <remarks> Country: URUGUAY </remarks>
  /// <remarks> Name: Peso Uruguayo </remarks>
  /// <remarks> Code: UYU </remarks>
  /// <remarks> Number: 858 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency UYU = Currency.Create("Peso Uruguayo", "UYU", 858, 2, new []{ "URUGUAY" });

  /// <summary>
  /// ISO4217 currency representation of Uruguay Peso en Unidades Indexadas (UI) (UYI).
  /// </summary>
  /// <remarks> Country: URUGUAY </remarks>
  /// <remarks> Name: Uruguay Peso en Unidades Indexadas (UI) </remarks>
  /// <remarks> Code: UYI </remarks>
  /// <remarks> Number: 940 </remarks>
  /// <remarks> Minor Units: 0 </remarks>
  public static readonly Currency UYI = Currency.Create("Uruguay Peso en Unidades Indexadas (UI)", "UYI", 940, 0, new []{ "URUGUAY" });

  /// <summary>
  /// ISO4217 currency representation of Unidad Previsional (UYW).
  /// </summary>
  /// <remarks> Country: URUGUAY </remarks>
  /// <remarks> Name: Unidad Previsional </remarks>
  /// <remarks> Code: UYW </remarks>
  /// <remarks> Number: 927 </remarks>
  /// <remarks> Minor Units: 4 </remarks>
  public static readonly Currency UYW = Currency.Create("Unidad Previsional", "UYW", 927, 4, new []{ "URUGUAY" });

  /// <summary>
  /// ISO4217 currency representation of Uzbekistan Sum (UZS).
  /// </summary>
  /// <remarks> Country: UZBEKISTAN </remarks>
  /// <remarks> Name: Uzbekistan Sum </remarks>
  /// <remarks> Code: UZS </remarks>
  /// <remarks> Number: 860 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency UZS = Currency.Create("Uzbekistan Sum", "UZS", 860, 2, new []{ "UZBEKISTAN" });

  /// <summary>
  /// ISO4217 currency representation of Vatu (VUV).
  /// </summary>
  /// <remarks> Country: VANUATU </remarks>
  /// <remarks> Name: Vatu </remarks>
  /// <remarks> Code: VUV </remarks>
  /// <remarks> Number: 548 </remarks>
  /// <remarks> Minor Units: 0 </remarks>
  public static readonly Currency VUV = Currency.Create("Vatu", "VUV", 548, 0, new []{ "VANUATU" });

  /// <summary>
  /// ISO4217 currency representation of Bolívar Soberano (VES).
  /// </summary>
  /// <remarks> Country: VENEZUELA (BOLIVARIAN REPUBLIC OF) </remarks>
  /// <remarks> Name: Bolívar Soberano </remarks>
  /// <remarks> Code: VES </remarks>
  /// <remarks> Number: 928 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency VES = Currency.Create("Bolívar Soberano", "VES", 928, 2, new []{ "VENEZUELA (BOLIVARIAN REPUBLIC OF)" });

  /// <summary>
  /// ISO4217 currency representation of Bolívar Soberano (VED).
  /// </summary>
  /// <remarks> Country: VENEZUELA (BOLIVARIAN REPUBLIC OF) </remarks>
  /// <remarks> Name: Bolívar Soberano </remarks>
  /// <remarks> Code: VED </remarks>
  /// <remarks> Number: 926 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency VED = Currency.Create("Bolívar Soberano", "VED", 926, 2, new []{ "VENEZUELA (BOLIVARIAN REPUBLIC OF)" });

  /// <summary>
  /// ISO4217 currency representation of Dong (VND).
  /// </summary>
  /// <remarks> Country: VIET NAM </remarks>
  /// <remarks> Name: Dong </remarks>
  /// <remarks> Code: VND </remarks>
  /// <remarks> Number: 704 </remarks>
  /// <remarks> Minor Units: 0 </remarks>
  public static readonly Currency VND = Currency.Create("Dong", "VND", 704, 0, new []{ "VIET NAM" });

  /// <summary>
  /// ISO4217 currency representation of Yemeni Rial (YER).
  /// </summary>
  /// <remarks> Country: YEMEN </remarks>
  /// <remarks> Name: Yemeni Rial </remarks>
  /// <remarks> Code: YER </remarks>
  /// <remarks> Number: 886 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency YER = Currency.Create("Yemeni Rial", "YER", 886, 2, new []{ "YEMEN" });

  /// <summary>
  /// ISO4217 currency representation of Zambian Kwacha (ZMW).
  /// </summary>
  /// <remarks> Country: ZAMBIA </remarks>
  /// <remarks> Name: Zambian Kwacha </remarks>
  /// <remarks> Code: ZMW </remarks>
  /// <remarks> Number: 967 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency ZMW = Currency.Create("Zambian Kwacha", "ZMW", 967, 2, new []{ "ZAMBIA" });

  /// <summary>
  /// ISO4217 currency representation of Zimbabwe Dollar (ZWL).
  /// </summary>
  /// <remarks> Country: ZIMBABWE </remarks>
  /// <remarks> Name: Zimbabwe Dollar </remarks>
  /// <remarks> Code: ZWL </remarks>
  /// <remarks> Number: 932 </remarks>
  /// <remarks> Minor Units: 2 </remarks>
  public static readonly Currency ZWL = Currency.Create("Zimbabwe Dollar", "ZWL", 932, 2, new []{ "ZIMBABWE" });

  /// <summary>
  /// All valid ISO4217 currencies
  /// </summary>
  public static readonly HashSet<Currency> Currencies = new HashSet<Currency>(new [] { AFN, EUR, ALL, DZD, USD, AOA, XCD, ARS, AMD, AWG, AUD, AZN, BSD, BHD, BDT, BBD, BYN, BZD, XOF, BMD, INR, BTN, BOB, BOV, BAM, BWP, NOK, BRL, BND, BGN, BIF, CVE, KHR, XAF, CAD, KYD, CLP, CLF, CNY, COP, COU, KMF, CDF, NZD, CRC, CUP, CUC, ANG, CZK, DKK, DJF, DOP, EGP, SVC, ERN, SZL, ETB, FKP, FJD, XPF, GMD, GEL, GHS, GIP, GTQ, GBP, GNF, GYD, HTG, HNL, HKD, HUF, ISK, IDR, IRR, IQD, ILS, JMD, JPY, JOD, KZT, KES, KPW, KRW, KWD, KGS, LAK, LBP, LSL, ZAR, LRD, LYD, CHF, MOP, MKD, MGA, MWK, MYR, MVR, MRU, MUR, MXN, MXV, MDL, MNT, MAD, MZN, MMK, NAD, NPR, NIO, NGN, OMR, PKR, PAB, PGK, PYG, PEN, PHP, PLN, QAR, RON, RUB, RWF, SHP, WST, STN, SAR, RSD, SCR, SLL, SLE, SGD, SBD, SOS, SSP, LKR, SDG, SRD, SEK, CHE, CHW, SYP, TWD, TJS, TZS, THB, TOP, TTD, TND, TRY, TMT, UGX, UAH, AED, USN, UYU, UYI, UYW, UZS, VUV, VES, VED, VND, YER, ZMW, ZWL });

  /// <summary>
  /// A case-insensitive, trailing and leading whitespace friendly lookup
  /// </summary>
  private static IReadOnlyDictionary<string, Currency> CurrencyCodeLookup = new ReadOnlyDictionary<string, Currency>(new Dictionary<string, Currency>(new InvariantCultureIgnoreCaseTrimmedEqualityStringComparer())
  {
    {"AFN", AFN},
    {"EUR", EUR},
    {"ALL", ALL},
    {"DZD", DZD},
    {"USD", USD},
    {"AOA", AOA},
    {"XCD", XCD},
    {"ARS", ARS},
    {"AMD", AMD},
    {"AWG", AWG},
    {"AUD", AUD},
    {"AZN", AZN},
    {"BSD", BSD},
    {"BHD", BHD},
    {"BDT", BDT},
    {"BBD", BBD},
    {"BYN", BYN},
    {"BZD", BZD},
    {"XOF", XOF},
    {"BMD", BMD},
    {"INR", INR},
    {"BTN", BTN},
    {"BOB", BOB},
    {"BOV", BOV},
    {"BAM", BAM},
    {"BWP", BWP},
    {"NOK", NOK},
    {"BRL", BRL},
    {"BND", BND},
    {"BGN", BGN},
    {"BIF", BIF},
    {"CVE", CVE},
    {"KHR", KHR},
    {"XAF", XAF},
    {"CAD", CAD},
    {"KYD", KYD},
    {"CLP", CLP},
    {"CLF", CLF},
    {"CNY", CNY},
    {"COP", COP},
    {"COU", COU},
    {"KMF", KMF},
    {"CDF", CDF},
    {"NZD", NZD},
    {"CRC", CRC},
    {"CUP", CUP},
    {"CUC", CUC},
    {"ANG", ANG},
    {"CZK", CZK},
    {"DKK", DKK},
    {"DJF", DJF},
    {"DOP", DOP},
    {"EGP", EGP},
    {"SVC", SVC},
    {"ERN", ERN},
    {"SZL", SZL},
    {"ETB", ETB},
    {"FKP", FKP},
    {"FJD", FJD},
    {"XPF", XPF},
    {"GMD", GMD},
    {"GEL", GEL},
    {"GHS", GHS},
    {"GIP", GIP},
    {"GTQ", GTQ},
    {"GBP", GBP},
    {"GNF", GNF},
    {"GYD", GYD},
    {"HTG", HTG},
    {"HNL", HNL},
    {"HKD", HKD},
    {"HUF", HUF},
    {"ISK", ISK},
    {"IDR", IDR},
    {"IRR", IRR},
    {"IQD", IQD},
    {"ILS", ILS},
    {"JMD", JMD},
    {"JPY", JPY},
    {"JOD", JOD},
    {"KZT", KZT},
    {"KES", KES},
    {"KPW", KPW},
    {"KRW", KRW},
    {"KWD", KWD},
    {"KGS", KGS},
    {"LAK", LAK},
    {"LBP", LBP},
    {"LSL", LSL},
    {"ZAR", ZAR},
    {"LRD", LRD},
    {"LYD", LYD},
    {"CHF", CHF},
    {"MOP", MOP},
    {"MKD", MKD},
    {"MGA", MGA},
    {"MWK", MWK},
    {"MYR", MYR},
    {"MVR", MVR},
    {"MRU", MRU},
    {"MUR", MUR},
    {"MXN", MXN},
    {"MXV", MXV},
    {"MDL", MDL},
    {"MNT", MNT},
    {"MAD", MAD},
    {"MZN", MZN},
    {"MMK", MMK},
    {"NAD", NAD},
    {"NPR", NPR},
    {"NIO", NIO},
    {"NGN", NGN},
    {"OMR", OMR},
    {"PKR", PKR},
    {"PAB", PAB},
    {"PGK", PGK},
    {"PYG", PYG},
    {"PEN", PEN},
    {"PHP", PHP},
    {"PLN", PLN},
    {"QAR", QAR},
    {"RON", RON},
    {"RUB", RUB},
    {"RWF", RWF},
    {"SHP", SHP},
    {"WST", WST},
    {"STN", STN},
    {"SAR", SAR},
    {"RSD", RSD},
    {"SCR", SCR},
    {"SLL", SLL},
    {"SLE", SLE},
    {"SGD", SGD},
    {"SBD", SBD},
    {"SOS", SOS},
    {"SSP", SSP},
    {"LKR", LKR},
    {"SDG", SDG},
    {"SRD", SRD},
    {"SEK", SEK},
    {"CHE", CHE},
    {"CHW", CHW},
    {"SYP", SYP},
    {"TWD", TWD},
    {"TJS", TJS},
    {"TZS", TZS},
    {"THB", THB},
    {"TOP", TOP},
    {"TTD", TTD},
    {"TND", TND},
    {"TRY", TRY},
    {"TMT", TMT},
    {"UGX", UGX},
    {"UAH", UAH},
    {"AED", AED},
    {"USN", USN},
    {"UYU", UYU},
    {"UYI", UYI},
    {"UYW", UYW},
    {"UZS", UZS},
    {"VUV", VUV},
    {"VES", VES},
    {"VED", VED},
    {"VND", VND},
    {"YER", YER},
    {"ZMW", ZMW},
    {"ZWL", ZWL},
  });

  /// <summary>
  /// Currency number lookup
  /// </summary>
  private static IReadOnlyDictionary<int, Currency> CurrencyNumberLookup = new ReadOnlyDictionary<int, Currency>(new Dictionary<int, Currency>
  {
    {971, AFN},
    {978, EUR},
    {8, ALL},
    {12, DZD},
    {840, USD},
    {973, AOA},
    {951, XCD},
    {32, ARS},
    {51, AMD},
    {533, AWG},
    {36, AUD},
    {944, AZN},
    {44, BSD},
    {48, BHD},
    {50, BDT},
    {52, BBD},
    {933, BYN},
    {84, BZD},
    {952, XOF},
    {60, BMD},
    {356, INR},
    {64, BTN},
    {68, BOB},
    {984, BOV},
    {977, BAM},
    {72, BWP},
    {578, NOK},
    {986, BRL},
    {96, BND},
    {975, BGN},
    {108, BIF},
    {132, CVE},
    {116, KHR},
    {950, XAF},
    {124, CAD},
    {136, KYD},
    {152, CLP},
    {990, CLF},
    {156, CNY},
    {170, COP},
    {970, COU},
    {174, KMF},
    {976, CDF},
    {554, NZD},
    {188, CRC},
    {192, CUP},
    {931, CUC},
    {532, ANG},
    {203, CZK},
    {208, DKK},
    {262, DJF},
    {214, DOP},
    {818, EGP},
    {222, SVC},
    {232, ERN},
    {748, SZL},
    {230, ETB},
    {238, FKP},
    {242, FJD},
    {953, XPF},
    {270, GMD},
    {981, GEL},
    {936, GHS},
    {292, GIP},
    {320, GTQ},
    {826, GBP},
    {324, GNF},
    {328, GYD},
    {332, HTG},
    {340, HNL},
    {344, HKD},
    {348, HUF},
    {352, ISK},
    {360, IDR},
    {364, IRR},
    {368, IQD},
    {376, ILS},
    {388, JMD},
    {392, JPY},
    {400, JOD},
    {398, KZT},
    {404, KES},
    {408, KPW},
    {410, KRW},
    {414, KWD},
    {417, KGS},
    {418, LAK},
    {422, LBP},
    {426, LSL},
    {710, ZAR},
    {430, LRD},
    {434, LYD},
    {756, CHF},
    {446, MOP},
    {807, MKD},
    {969, MGA},
    {454, MWK},
    {458, MYR},
    {462, MVR},
    {929, MRU},
    {480, MUR},
    {484, MXN},
    {979, MXV},
    {498, MDL},
    {496, MNT},
    {504, MAD},
    {943, MZN},
    {104, MMK},
    {516, NAD},
    {524, NPR},
    {558, NIO},
    {566, NGN},
    {512, OMR},
    {586, PKR},
    {590, PAB},
    {598, PGK},
    {600, PYG},
    {604, PEN},
    {608, PHP},
    {985, PLN},
    {634, QAR},
    {946, RON},
    {643, RUB},
    {646, RWF},
    {654, SHP},
    {882, WST},
    {930, STN},
    {682, SAR},
    {941, RSD},
    {690, SCR},
    {694, SLL},
    {925, SLE},
    {702, SGD},
    {90, SBD},
    {706, SOS},
    {728, SSP},
    {144, LKR},
    {938, SDG},
    {968, SRD},
    {752, SEK},
    {947, CHE},
    {948, CHW},
    {760, SYP},
    {901, TWD},
    {972, TJS},
    {834, TZS},
    {764, THB},
    {776, TOP},
    {780, TTD},
    {788, TND},
    {949, TRY},
    {934, TMT},
    {800, UGX},
    {980, UAH},
    {784, AED},
    {997, USN},
    {858, UYU},
    {940, UYI},
    {927, UYW},
    {860, UZS},
    {548, VUV},
    {928, VES},
    {926, VED},
    {704, VND},
    {886, YER},
    {967, ZMW},
    {932, ZWL},
  });
}

#nullable restore

